server:
  port: 9080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:9081
          predicates:
            - Path=/auth/**
        - id: notification-service
          uri: http://notification-service:9082
          predicates:
            - Path=/notifications/**
          filters:
            - name: AuthFilter

app:
  global:
    validation:
      email: ^[a-zA-Z0-9._-]+@([a-zA-Z0-9]+\\.){1,2}[a-zA-Z]{2,15}$
    security:
      jwt:
        secret: idemforever